import Head from "next/head";
import Navbar from "../components/Navbar";
import Product from "../components/Product";

import data from "../data.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="container mx-auto text-center ">
        <h1 className="mt-4 text-4xl text-center">Our Products</h1>
        <div className="grid grid-cols-1 gap-4 mt-4 md:grid-cols-3">
          {data.map((product) => (
            <Product product={product} />
          ))}
        </div>
      </section>
    </div>
  );
}
